spring.application.name=api-sustentavel

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/apisustentavel
spring.datasource.username=postgres
spring.datasource.password=admin123

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html